import type { Fingerprint } from "../types.js";

export interface TokensCssOptions {
  /** Source path (e.g. "./fingerprint.md") — surfaced in the provenance header. */
  sourcePath?: string;
  /** Generator version string — surfaced in the provenance header. */
  generator?: string;
}

/**
 * Derive a CSS custom-property sheet from a fingerprint.
 * Emits only dimensions the fingerprint actually captures.
 *
 * The file opens with a provenance header identifying the generator,
 * source fingerprint, and timestamp. Hand-edits will silently drift from
 * the source — the header warns readers not to edit.
 */
export function buildTokensCss(
  fingerprint: Fingerprint,
  options: TokensCssOptions = {},
): string {
  const sections: string[] = [];

  const dominant = fingerprint.palette?.dominant ?? [];
  if (dominant.length) {
    sections.push(
      block(
        "Dominant brand",
        dominant.map((c) => `--brand-${slug(c.role)}: ${c.value};`),
      ),
    );
  }

  const semantic = fingerprint.palette?.semantic ?? [];
  if (semantic.length) {
    sections.push(
      block(
        "Semantic colors",
        semantic.map((c) => `--color-${slug(c.role)}: ${c.value};`),
      ),
    );
  }

  const neutrals = fingerprint.palette?.neutrals?.steps ?? [];
  if (neutrals.length) {
    sections.push(
      block(
        "Neutral ramp",
        neutrals.map((hex, i) => `--neutral-${i}: ${hex};`),
      ),
    );
  }

  const spacing = fingerprint.spacing?.scale ?? [];
  if (spacing.length) {
    sections.push(
      block(
        "Spacing scale",
        spacing.map((n, i) => `--space-${i}: ${n}px;`),
      ),
    );
  }

  const sizeRamp = fingerprint.typography?.sizeRamp ?? [];
  if (sizeRamp.length) {
    sections.push(
      block(
        "Typography scale",
        sizeRamp.map((n, i) => `--text-${i}: ${n}px;`),
      ),
    );
  }

  const families = fingerprint.typography?.families ?? [];
  if (families.length) {
    sections.push(
      block("Font families", [`--font-sans: ${families.join(", ")};`]),
    );
  }

  const radii = fingerprint.surfaces?.borderRadii ?? [];
  if (radii.length) {
    sections.push(
      block(
        "Border radii",
        radii.map((n, i) => `--radius-${i}: ${n}px;`),
      ),
    );
  }

  const generator = options.generator ?? "ghost";
  const source = options.sourcePath ?? "fingerprint.md";
  const timestamp = fingerprint.timestamp ?? new Date().toISOString();
  const header = [
    "/*",
    ` * Generated by ${generator} from ${source} on ${timestamp}`,
    " * DO NOT EDIT — regenerate with `ghost emit context-bundle`.",
    " */",
  ].join("\n");
  const body = sections.length
    ? `:root {\n${sections.join("\n\n")}\n}`
    : ":root {}";
  return `${header}\n\n${body}\n`;
}

function block(label: string, lines: string[]): string {
  const indented = lines.map((l) => `  ${l}`).join("\n");
  return `  /* ${label} */\n${indented}`;
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
