export type {
  ColorRamp,
  ComponentMeta,
  CompositeCluster,
  CompositeComparison,
  CompositeMember,
  CompositePair,
  CSSToken,
  CSSVarsMap,
  DesignDecision,
  DesignObservation,
  DetectedFormat,
  DimensionAck,
  DimensionDelta,
  DimensionStance,
  DivergenceClass,
  DriftVector,
  DriftVelocity,
  EmbeddingConfig,
  EnrichedComparison,
  EnrichedExpression,
  Expression,
  ExpressionComparison,
  ExpressionHistoryEntry,
  ExtractedFile,
  ExtractedMaterial,
  Extractor,
  ExtractorOptions,
  FontDescriptor,
  GhostConfig,
  NormalizedToken,
  Registry,
  RegistryFile,
  RegistryItem,
  RegistryItemType,
  ResolvedRegistry,
  RoleCandidate,
  RuleSeverity,
  SampledFile,
  SampledMaterial,
  SemanticColor,
  SourceInfo,
  StructureDrift,
  SyncManifest,
  Target,
  TargetOptions,
  TargetType,
  TemporalComparison,
  TokenCategory,
  TokenFormat,
  ValueDrift,
} from "@ghost/core";
export {
  compareExpressions,
  computeEmbedding,
  computeSemanticEmbedding,
  describeExpression,
  embeddingDistance,
  inferSemanticRole,
} from "@ghost/core";
// --- Deprecation shim: expression authoring + context emit moved to `ghost-expression`.
// Re-exported here for one major-version cycle so library consumers can update
// their imports gradually. New code should `import from "ghost-expression"`.
export type {
  BodyData,
  ColorChange,
  ContextFormat,
  DecisionChange,
  EmitReviewInput,
  ExpressionLayout,
  ExpressionLayoutSection,
  ExpressionMeta,
  FrontmatterData,
  FrontmatterShape,
  LintIssue,
  LintOptions,
  LintReport,
  LintSeverity,
  ParsedExpression,
  SemanticDiff,
  TokenChange,
  WriteContextOptions,
  WriteContextResult,
} from "ghost-expression";
export {
  buildSkillMd,
  buildTokensCss,
  diffExpressions,
  EMBEDDING_FRAGMENT_FILENAME,
  EXPRESSION_FILENAME,
  embeddingSiblingPath,
  emitReviewCommand,
  FrontmatterSchema,
  findFragmentLinks,
  formatLayout,
  formatSemanticDiff,
  layoutExpression,
  lintExpression,
  loadEmbeddingFragment,
  loadExpression,
  parseBody,
  parseExpression,
  resolveEmbeddingReference,
  serializeEmbeddingFragment,
  serializeExpression,
  splitRaw,
  toJsonSchema,
  validateFrontmatter,
  writeContextBundle,
} from "ghost-expression";
export type { CompareOptions, CompareResult } from "./compare.js";
export { compare } from "./compare.js";
export { defineConfig, loadConfig, resolveTarget } from "./config.js";
export type {
  CheckBoundsOptions,
  CompositeClusterOptions,
} from "./evolution/index.js";
export {
  acknowledge,
  appendHistory,
  checkBounds,
  compareComposite,
  computeDriftVectors,
  computeTemporalComparison,
  DIMENSION_RANGES,
  emitExpression,
  normalizeTrackedSource,
  readHistory,
  readRecentHistory,
  readSyncManifest,
  resolveTrackedExpression,
  writeSyncManifest,
} from "./evolution/index.js";
export {
  formatCompositeComparison,
  formatCompositeComparisonJSON,
} from "./reporters/composite.js";
export {
  formatComparison,
  formatComparisonJSON,
  formatExpression,
  formatExpressionJSON,
} from "./reporters/expression.js";
export {
  formatTemporalComparison,
  formatTemporalComparisonJSON,
} from "./reporters/temporal.js";
