export type { CompareOptions, CompareResult } from "./compare.js";
export { compare } from "./compare.js";
export { defineConfig, loadConfig, resolveTarget } from "./config.js";
export type {
  ContextFormat,
  EmitReviewInput,
  WriteContextOptions,
  WriteContextResult,
} from "./context/index.js";
export {
  buildSkillMd,
  buildTokensCss,
  emitReviewCommand,
  writeContextBundle,
} from "./context/index.js";
export type { RoleCandidate } from "./embedding/index.js";
export {
  compareFingerprints,
  computeEmbedding,
  computeSemanticEmbedding,
  describeFingerprint,
  embeddingDistance,
  inferSemanticRole,
} from "./embedding/index.js";
export type {
  CheckBoundsOptions,
  CompositeClusterOptions,
} from "./evolution/index.js";
export {
  acknowledge,
  appendHistory,
  checkBounds,
  compareComposite,
  computeDriftVectors,
  computeTemporalComparison,
  DIMENSION_RANGES,
  emitFingerprint,
  normalizeParentSource,
  readHistory,
  readRecentHistory,
  readSyncManifest,
  resolveParent,
  writeSyncManifest,
} from "./evolution/index.js";
export type {
  BodyData,
  ColorChange,
  DecisionChange,
  FingerprintMeta,
  FrontmatterData,
  FrontmatterShape,
  LintIssue,
  LintOptions,
  LintReport,
  LintSeverity,
  ParsedFingerprint,
  SemanticDiff,
  TokenChange,
} from "./fingerprint/index.js";
export {
  diffFingerprints,
  EMBEDDING_FRAGMENT_FILENAME,
  embeddingSiblingPath,
  FINGERPRINT_FILENAME,
  FrontmatterSchema,
  findFragmentLinks,
  formatSemanticDiff,
  lintFingerprint,
  loadEmbeddingFragment,
  loadFingerprint,
  parseBody,
  parseFingerprint,
  resolveEmbeddingReference,
  serializeEmbeddingFragment,
  serializeFingerprint,
  splitRaw,
  toJsonSchema,
  validateFrontmatter,
} from "./fingerprint/index.js";
export {
  formatCompositeComparison,
  formatCompositeComparisonJSON,
} from "./reporters/composite.js";
export {
  formatComparison,
  formatComparisonJSON,
  formatFingerprint,
  formatFingerprintJSON,
} from "./reporters/fingerprint.js";
export {
  formatTemporalComparison,
  formatTemporalComparisonJSON,
} from "./reporters/temporal.js";
export type {
  ColorRamp,
  ComponentMeta,
  CompositeCluster,
  CompositeComparison,
  CompositeMember,
  CompositePair,
  CSSToken,
  CSSVarsMap,
  DesignDecision,
  DesignObservation,
  DetectedFormat,
  DimensionAck,
  DimensionDelta,
  DimensionStance,
  DivergenceClass,
  DriftVector,
  DriftVelocity,
  EmbeddingConfig,
  EnrichedComparison,
  EnrichedFingerprint,
  ExtractedFile,
  ExtractedMaterial,
  Extractor,
  ExtractorOptions,
  Fingerprint,
  FingerprintComparison,
  FingerprintHistoryEntry,
  FontDescriptor,
  GhostConfig,
  NormalizedToken,
  Registry,
  RegistryFile,
  RegistryItem,
  RegistryItemType,
  ResolvedRegistry,
  RuleSeverity,
  SampledFile,
  SampledMaterial,
  SemanticColor,
  SourceInfo,
  StructureDrift,
  SyncManifest,
  Target,
  TargetOptions,
  TargetType,
  TemporalComparison,
  TokenCategory,
  TokenFormat,
  ValueDrift,
} from "./types.js";
