"use client";

import { useStaggerReveal } from "ghost-ui";
import { BookOpen, Compass, Rocket } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "react-router";
import { AnimatedPageHeader } from "@/components/docs/animated-page-header";
import { SectionWrapper } from "@/components/docs/wrappers";

const cards: {
  name: string;
  href: string;
  description: string;
  icon: ReactNode;
}[] = [
  {
    name: "Get started",
    href: "/docs/getting-started",
    description:
      "Install the CLIs and write your first map.md alongside expression.md.",
    icon: <Rocket className="size-8" strokeWidth={1.5} />,
  },
  {
    name: "CLI reference",
    href: "/docs/cli#ghost-map--topology",
    description:
      "inventory (raw repo signals as JSON) and lint (validate map.md against ghost.map/v1).",
    icon: <BookOpen className="size-8" strokeWidth={1.5} />,
  },
  {
    name: "Skill bundle",
    href: "https://github.com/block/ghost/tree/main/packages/ghost-map/src/skill-bundle",
    description:
      "The map recipe — the agent reads inventory and synthesizes the prose layer of map.md.",
    icon: <Compass className="size-8" strokeWidth={1.5} />,
  },
];

export default function GhostMapLanding() {
  const ref = useStaggerReveal<HTMLDivElement>(".tool-card", {
    stagger: 0.06,
    y: 30,
    duration: 0.7,
  });

  return (
    <SectionWrapper>
      <AnimatedPageHeader
        kicker="ghost-map"
        title="Topology"
        description="The navigation card every Ghost tool reads. map.md answers “where is the design system, which folders matter?” — language-agnostic, validated against ghost.map/v1, generated by the host agent from the deterministic inventory."
      />

      <div
        ref={ref}
        className="grid gap-4 md:grid-cols-3 pb-16 overflow-visible"
      >
        {cards.map((item) => (
          <Link
            key={item.href}
            to={item.href}
            className="tool-card group rounded-[var(--radius-card-sm)] border border-border-card hover:border-foreground/25 bg-card p-10 transition-colors duration-300"
          >
            <div className="mb-6 text-muted-foreground group-hover:text-foreground transition-colors duration-200">
              {item.icon}
            </div>
            <span className="relative inline-block font-display text-lg font-bold tracking-tight">
              <span className="relative z-10 transition-colors duration-300 group-hover:text-background">
                {item.name}
              </span>
              <span className="absolute inset-0 bg-foreground origin-left scale-x-0 group-hover:scale-x-100 transition-transform duration-300 ease-out" />
            </span>
            <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
              {item.description}
            </p>
          </Link>
        ))}
      </div>
    </SectionWrapper>
  );
}
