// --- Embedding primitives ---

export type {
  GhostCheck,
  GhostCheckAppliesTo,
  GhostCheckDerivation,
  GhostCheckDerivationCompositionRef,
  GhostCheckDerivationInventoryRef,
  GhostCheckDerivationProseRef,
  GhostCheckDetector,
  GhostCheckDetectorType,
  GhostCheckEvidence,
  GhostCheckSeverity,
  GhostCheckStatus,
  GhostChecksDocument,
  GhostChecksFingerprintContext,
  GhostChecksLintIssue,
  GhostChecksLintOptions,
  GhostChecksLintReport,
  GhostChecksLintSeverity,
  RoutedGhostCheck,
} from "./checks/index.js";
// --- Checks (ghost.checks/v2) ---
export {
  GHOST_CHECKS_FILENAME,
  GHOST_CHECKS_SCHEMA,
  GhostCheckDerivationSchema,
  GhostCheckSchema,
  GhostChecksSchema,
  lintGhostChecks,
  matchesGhostPath,
  normalizeGhostPath,
  routeGhostChecksForPath,
  routeGhostPathToScopes,
} from "./checks/index.js";
// --- Decision vocabulary (controlled list for fleet aggregation) ---
export {
  CANONICAL_DECISION_DIMENSIONS,
  type CanonicalDecisionDimension,
  closestCanonical,
  isCanonicalDimension,
  resolveDecisionKind,
} from "./decision-vocabulary.js";
export type { CompareOptions, RoleCandidate } from "./embedding/index.js";
export {
  classifyContrast,
  classifySaturation,
  colorToSemanticColor,
  compareFingerprints,
  computeDriftVectors,
  computeEmbedding,
  computeSemanticEmbedding,
  contrastScore,
  DIMENSION_RANGES,
  describeFingerprint,
  embeddingDistance,
  embedTexts,
  inferSemanticRole,
  parseColorToOklch,
  saturationScore,
} from "./embedding/index.js";
// --- Map (ghost.map/v2) ---
export {
  CACHE_DIRNAME,
  CONFIG_FILENAME,
  DECISIONS_DIRNAME,
  FINGERPRINT_FILENAME,
  FINGERPRINT_PACKAGE_DIR,
  FINGERPRINT_YML_FILENAME,
  type FingerprintPackagePaths,
  INTENT_FILENAME,
  PATTERNS_FILENAME,
  RESOURCES_FILENAME,
} from "./fingerprint-package.js";
// --- Map (ghost.map/v2) ---
export {
  type GitInfo,
  getEffectiveMapScopes,
  type InventoryOutput,
  type LanguageHistogramEntry,
  MAP_FILENAME,
  type MapFeatureArea,
  type MapFrontmatter,
  MapFrontmatterSchema,
  type MapScope,
  MapScopeSchema,
  REQUIRED_BODY_SECTIONS,
  type RequiredBodySection,
  slugifyScopeId,
  type TopLevelEntry,
} from "./map/index.js";
// --- Memory (ghost.decision/v1) ---
export type {
  GhostDecisionDocument,
  GhostDecisionLintIssue,
  GhostDecisionLintReport,
  GhostDecisionLintSeverity,
  GhostDecisionStatus,
  GhostExperienceEvidence,
  GhostExperienceScope,
} from "./memory/index.js";
export {
  GHOST_DECISION_SCHEMA,
  GHOST_DECISIONS_DIRNAME,
  GhostDecisionSchema,
  GhostExperienceEvidenceSchema,
  GhostExperienceScopeSchema,
  lintGhostDecision,
} from "./memory/index.js";
// --- Patterns (ghost.patterns/v1) ---
export type {
  GhostCompositionAnatomy,
  GhostCompositionPattern,
  GhostPatternEvidence,
  GhostPatternsDocument,
  GhostPatternsLintIssue,
  GhostPatternsLintReport,
  GhostPatternsLintSeverity,
  GhostSurfaceTypePattern,
} from "./patterns/index.js";
export {
  GHOST_PATTERNS_FILENAME,
  GHOST_PATTERNS_SCHEMA,
  GhostCompositionAnatomySchema,
  GhostCompositionPatternSchema,
  GhostPatternEvidenceSchema,
  GhostPatternsSchema,
  GhostSurfaceTypePatternSchema,
  lintGhostPatterns,
} from "./patterns/index.js";
// --- Perceptual prior (drift severity calibration) ---
export {
  computeCheckSeverity,
  DEFAULT_MATCH,
  DEFAULT_TOLERANCE,
  escalateForPresence,
  escalateTier,
  PERCEPTUAL_TIER,
  type PerceptualTier,
  resolveMatchShape,
  resolveTolerance,
  TIER_SEVERITY,
  tierForCanonical,
} from "./perceptual-prior.js";
// --- Resources (ghost.resources/v1) ---
export type {
  GhostResourceRef,
  GhostResourcesDocument,
  GhostResourcesLintIssue,
  GhostResourcesLintReport,
  GhostResourcesLintSeverity,
  GhostSurfaceResource,
} from "./resources/index.js";
export {
  GHOST_RESOURCES_FILENAME,
  GHOST_RESOURCES_SCHEMA,
  GhostResourceRefSchema,
  GhostResourcesSchema,
  GhostSurfaceResourceSchema,
  lintGhostResources,
} from "./resources/index.js";
// --- Skill bundle loader ---
export type { SkillBundleFile } from "./skill-bundle-loader.js";
export { loadSkillBundle } from "./skill-bundle-loader.js";
// --- Survey (ghost.survey/v2) ---
export {
  type BreakpointSpec,
  type ColorSpec,
  ColorSpecSchema,
  type ComponentEvidenceSummary,
  type ComponentRow,
  ComponentRowSchema,
  type CountSummary,
  catalogSurveyValues,
  componentRowId,
  formatSurveyCatalogMarkdown,
  formatSurveySummaryMarkdown,
  type LayoutPrimitiveSpec,
  lintSurvey,
  type MotionSpec,
  mergeSurveys,
  type RadiusSpec,
  RECOMMENDED_VALUE_KINDS,
  type RecommendedValueKind,
  type Resolution,
  ResolutionSchema,
  type ResolutionSummary,
  type RowBase,
  recomputeSurveyIds,
  type ScalarUnit,
  type ShadowSpec,
  type SpacingSpec,
  SURVEY_FILENAME,
  type Survey,
  type SurveyCatalogCounts,
  type SurveyCatalogKind,
  type SurveyCatalogOptions,
  type SurveyCatalogValue,
  type SurveyComponentsSummary,
  type SurveyLintIssue,
  type SurveyLintReport,
  type SurveyLintSeverity,
  SurveySchema,
  type SurveySource,
  SurveySourceSchema,
  type SurveySourceSummary,
  type SurveySummary,
  type SurveySummaryBudget,
  type SurveySummaryCounts,
  type SurveySummaryOptions,
  type SurveyTokensSummary,
  type SurveyUiSurfacesSummary,
  type SurveyValueCatalog,
  type SurveyValuesSummary,
  summarizeSurvey,
  type TokenEvidenceSummary,
  type TokenRow,
  TokenRowSchema,
  type TypographySpec,
  tokenRowId,
  type UiSurfaceClassification,
  UiSurfaceClassificationSchema,
  type UiSurfaceComposition,
  UiSurfaceCompositionSchema,
  type UiSurfaceDensity,
  type UiSurfaceEvidenceSummary,
  type UiSurfaceGroupSummary,
  type UiSurfaceKind,
  UiSurfaceKindSchema,
  type UiSurfaceLayoutShape,
  type UiSurfaceRenderability,
  UiSurfaceRenderabilitySchema,
  type UiSurfaceRow,
  UiSurfaceRowSchema,
  type UiSurfaceSignals,
  UiSurfaceSignalsSchema,
  type UnknownSpec,
  uiSurfaceRowId,
  type ValueEvidenceSummary,
  type ValueKindSummary,
  type ValueRow,
  ValueRowSchema,
  type ValueSpec,
  ValueSpecSchema,
  valueRowId,
} from "./survey/index.js";
// --- Target resolution ---
export { resolveTarget } from "./target-resolver.js";

// --- Shared types ---
export type {
  Check,
  CheckKind,
  CheckMatchShape,
  ColorRamp,
  ComponentMeta,
  CompositeCluster,
  CompositeComparison,
  CompositeMember,
  CompositePair,
  CSSToken,
  CSSVarsMap,
  DesignDecision,
  DesignObservation,
  DetectedFormat,
  DimensionAck,
  DimensionDelta,
  DimensionStance,
  DivergenceClass,
  DriftSeverity,
  DriftVector,
  DriftVelocity,
  EmbeddingConfig,
  EnrichedComparison,
  EnrichedFingerprint,
  ExtractedFile,
  ExtractedMaterial,
  Extractor,
  ExtractorOptions,
  Fingerprint,
  FingerprintComparison,
  FingerprintHistoryEntry,
  FingerprintReferences,
  FontDescriptor,
  GhostConfig,
  NormalizedToken,
  Registry,
  RegistryFile,
  RegistryItem,
  RegistryItemType,
  ResolvedRegistry,
  RuleSeverity,
  SampledFile,
  SampledMaterial,
  SemanticColor,
  SourceInfo,
  StructureDrift,
  SyncManifest,
  Target,
  TargetOptions,
  TargetType,
  TemporalComparison,
  TokenCategory,
  TokenFormat,
  ValueDrift,
} from "./types.js";
