// --- Embedding primitives ---

// --- Bucket (ghost.bucket/v1) ---
export {
  type BreakpointSpec,
  BUCKET_FILENAME,
  type Bucket,
  type BucketLintIssue,
  type BucketLintReport,
  type BucketLintSeverity,
  BucketSchema,
  type BucketSource,
  BucketSourceSchema,
  type ColorSpec,
  ColorSpecSchema,
  type ComponentRow,
  ComponentRowSchema,
  componentRowId,
  type LayoutPrimitiveSpec,
  lintBucket,
  type MotionSpec,
  mergeBuckets,
  type RadiusSpec,
  RECOMMENDED_VALUE_KINDS,
  type RecommendedValueKind,
  type RowBase,
  recomputeBucketIds,
  type ScalarUnit,
  type ShadowSpec,
  type SpacingSpec,
  type TokenRow,
  TokenRowSchema,
  type TypographySpec,
  tokenRowId,
  type UnknownSpec,
  type ValueRow,
  ValueRowSchema,
  type ValueSpec,
  ValueSpecSchema,
  valueRowId,
} from "./bucket/index.js";
// --- Decision vocabulary (controlled list for fleet aggregation) ---
export {
  CANONICAL_DECISION_DIMENSIONS,
  type CanonicalDecisionDimension,
  closestCanonical,
  isCanonicalDimension,
  resolveDecisionKind,
} from "./decision-vocabulary.js";
export type { CompareOptions, RoleCandidate } from "./embedding/index.js";
export {
  classifyContrast,
  classifySaturation,
  colorToSemanticColor,
  compareExpressions,
  computeDriftVectors,
  computeEmbedding,
  computeSemanticEmbedding,
  contrastScore,
  DIMENSION_RANGES,
  describeExpression,
  embeddingDistance,
  embedTexts,
  inferSemanticRole,
  parseColorToOklch,
  saturationScore,
} from "./embedding/index.js";
// --- Map (ghost.map/v1) ---
export {
  type GitInfo,
  type InventoryOutput,
  type LanguageHistogramEntry,
  MAP_FILENAME,
  type MapFrontmatter,
  MapFrontmatterSchema,
  REQUIRED_BODY_SECTIONS,
  type RequiredBodySection,
  type TopLevelEntry,
} from "./map/index.js";
// --- Skill bundle loader ---
export type { SkillBundleFile } from "./skill-bundle-loader.js";
export { loadSkillBundle } from "./skill-bundle-loader.js";
// --- Target resolution ---
export { resolveTarget } from "./target-resolver.js";

// --- Shared types ---
export type {
  ColorRamp,
  ComponentMeta,
  CompositeCluster,
  CompositeComparison,
  CompositeMember,
  CompositePair,
  CSSToken,
  CSSVarsMap,
  DesignDecision,
  DesignObservation,
  DetectedFormat,
  DimensionAck,
  DimensionDelta,
  DimensionStance,
  DivergenceClass,
  DriftVector,
  DriftVelocity,
  EmbeddingConfig,
  EnrichedComparison,
  EnrichedExpression,
  Expression,
  ExpressionComparison,
  ExpressionHistoryEntry,
  ExtractedFile,
  ExtractedMaterial,
  Extractor,
  ExtractorOptions,
  FontDescriptor,
  GhostConfig,
  NormalizedToken,
  Registry,
  RegistryFile,
  RegistryItem,
  RegistryItemType,
  ResolvedRegistry,
  RuleSeverity,
  SampledFile,
  SampledMaterial,
  SemanticColor,
  SourceInfo,
  StructureDrift,
  SyncManifest,
  Target,
  TargetOptions,
  TargetType,
  TemporalComparison,
  TokenCategory,
  TokenFormat,
  ValueDrift,
} from "./types.js";
