export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  preview: {
    accent: string;
    background: string;
    text: string;
    muted: string;
  };
  variables: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
}

export const PRESETS: ThemePreset[] = [
  {
    id: "default",
    name: "Default",
    description: "Monochromatic grayscale",
    preview: {
      accent: "#1a1a1a",
      background: "#ffffff",
      text: "#1a1a1a",
      muted: "#f0f0f0",
    },
    variables: {
      light: {},
      dark: {},
    },
  },
  {
    id: "warm-sand",
    name: "Warm Sand",
    description: "Earthy terracotta warmth",
    preview: {
      accent: "#9C5930",
      background: "#FBF5EC",
      text: "#3D2B1F",
      muted: "#F0E4D4",
    },
    variables: {
      light: {
        "--background-accent": "#9C5930",
        "--border-accent": "#9C5930",
        "--text-accent": "#9C5930",
        "--background-default": "#FBF5EC",
        "--background-alt": "#F5ECDF",
        "--background-medium": "#C4A882",
        "--background-muted": "#F0E4D4",
        "--background-inverse": "#3D2B1F",
        "--border-default": "#E2D4C0",
        "--border-input": "#D4C2AA",
        "--border-input-hover": "#C4A882",
        "--border-strong": "#3D2B1F",
        "--border-card": "#E2D4C0",
        "--border-inverse": "#3D2B1F",
        "--text-default": "#3D2B1F",
        "--text-muted": "#8B7355",
        "--text-alt": "#6B5940",
        "--text-inverse": "#FBF5EC",
        "--chart-1": "#D4853A",
        "--chart-2": "#7B9EA8",
        "--chart-3": "#C46B5A",
        "--chart-4": "#A8856B",
        "--chart-5": "#8BAA72",
      },
      dark: {
        "--background-accent": "#D4853A",
        "--border-accent": "#D4853A",
        "--text-accent": "#D4853A",
        "--background-default": "#1C1410",
        "--background-alt": "#2A1F18",
        "--background-medium": "#4A382A",
        "--background-muted": "#2A1F18",
        "--background-inverse": "#FBF5EC",
        "--border-default": "#3A2C20",
        "--border-input": "#3A2C20",
        "--border-input-hover": "#5A4530",
        "--border-strong": "#D4853A",
        "--border-card": "#3A2C20",
        "--border-inverse": "#FBF5EC",
        "--text-default": "#F0E4D4",
        "--text-muted": "#8B7355",
        "--text-alt": "#8B7355",
        "--text-inverse": "#1C1410",
        "--chart-1": "#D4853A",
        "--chart-2": "#7B9EA8",
        "--chart-3": "#C46B5A",
        "--chart-4": "#A8856B",
        "--chart-5": "#8BAA72",
      },
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Cool blues and teals",
    preview: {
      accent: "#1B6B8A",
      background: "#F4F9FB",
      text: "#0F3442",
      muted: "#E4F0F5",
    },
    variables: {
      light: {
        "--background-accent": "#1B6B8A",
        "--border-accent": "#1B6B8A",
        "--text-accent": "#1B6B8A",
        "--background-default": "#F4F9FB",
        "--background-alt": "#EAF3F8",
        "--background-medium": "#8BB8CA",
        "--background-muted": "#E4F0F5",
        "--background-inverse": "#0F3442",
        "--border-default": "#C8DEE8",
        "--border-input": "#B0D0DE",
        "--border-input-hover": "#8BB8CA",
        "--border-strong": "#0F3442",
        "--border-card": "#C8DEE8",
        "--border-inverse": "#0F3442",
        "--text-default": "#0F3442",
        "--text-muted": "#5A8A9C",
        "--text-alt": "#3A6A7C",
        "--text-inverse": "#F4F9FB",
        "--chart-1": "#2E9AB8",
        "--chart-2": "#5B78D8",
        "--chart-3": "#E07A5F",
        "--chart-4": "#7BC4B8",
        "--chart-5": "#A8C256",
      },
      dark: {
        "--background-accent": "#3AB4D8",
        "--border-accent": "#3AB4D8",
        "--text-accent": "#3AB4D8",
        "--background-default": "#0A1E28",
        "--background-alt": "#112A36",
        "--background-medium": "#2A5060",
        "--background-muted": "#112A36",
        "--background-inverse": "#F4F9FB",
        "--border-default": "#1A3A4A",
        "--border-input": "#1A3A4A",
        "--border-input-hover": "#3A6070",
        "--border-strong": "#3AB4D8",
        "--border-card": "#1A3A4A",
        "--border-inverse": "#F4F9FB",
        "--text-default": "#E4F0F5",
        "--text-muted": "#5A8A9C",
        "--text-alt": "#5A8A9C",
        "--text-inverse": "#0A1E28",
        "--chart-1": "#3AB4D8",
        "--chart-2": "#7B92E8",
        "--chart-3": "#E07A5F",
        "--chart-4": "#7BC4B8",
        "--chart-5": "#A8C256",
      },
    },
  },
  {
    id: "midnight-luxe",
    name: "Midnight Luxe",
    description: "Deep purples and golds",
    preview: {
      accent: "#C5A24D",
      background: "#F8F6F9",
      text: "#1E1528",
      muted: "#EDE8F2",
    },
    variables: {
      light: {
        "--background-accent": "#1E1528",
        "--border-accent": "#1E1528",
        "--text-accent": "#1E1528",
        "--background-default": "#F8F6F9",
        "--background-alt": "#F0ECF4",
        "--background-medium": "#B8A8C8",
        "--background-muted": "#EDE8F2",
        "--background-inverse": "#1E1528",
        "--border-default": "#DDD4E6",
        "--border-input": "#CCC0D8",
        "--border-input-hover": "#B8A8C8",
        "--border-strong": "#1E1528",
        "--border-card": "#DDD4E6",
        "--border-inverse": "#1E1528",
        "--text-default": "#1E1528",
        "--text-muted": "#7A6B8A",
        "--text-alt": "#5A4B6A",
        "--text-inverse": "#F8F6F9",
        "--background-warning": "#C5A24D",
        "--chart-1": "#C5A24D",
        "--chart-2": "#8B6CC1",
        "--chart-3": "#D76A7A",
        "--chart-4": "#5E8EC5",
        "--chart-5": "#7CB88A",
      },
      dark: {
        "--background-accent": "#C5A24D",
        "--border-accent": "#C5A24D",
        "--text-accent": "#C5A24D",
        "--background-default": "#0E0A14",
        "--background-alt": "#1A1224",
        "--background-medium": "#3A2A50",
        "--background-muted": "#1A1224",
        "--background-inverse": "#F8F6F9",
        "--border-default": "#2A1E3A",
        "--border-input": "#2A1E3A",
        "--border-input-hover": "#4A3A60",
        "--border-strong": "#C5A24D",
        "--border-card": "#2A1E3A",
        "--border-inverse": "#F8F6F9",
        "--text-default": "#EDE8F2",
        "--text-muted": "#7A6B8A",
        "--text-alt": "#7A6B8A",
        "--text-inverse": "#0E0A14",
        "--background-warning": "#C5A24D",
        "--chart-1": "#C5A24D",
        "--chart-2": "#A88DE0",
        "--chart-3": "#E08090",
        "--chart-4": "#7AAEE5",
        "--chart-5": "#8BD09A",
      },
    },
  },
  {
    id: "neon-brutalist",
    name: "Neon Brutalist",
    description: "High contrast, sharp edges",
    preview: {
      accent: "#FF3A00",
      background: "#ffffff",
      text: "#000000",
      muted: "#F0F0F0",
    },
    variables: {
      light: {
        "--background-accent": "#FF3A00",
        "--border-accent": "#FF3A00",
        "--text-accent": "#FF3A00",
        "--background-default": "#ffffff",
        "--background-alt": "#F0F0F0",
        "--background-medium": "#CCCCCC",
        "--background-muted": "#F0F0F0",
        "--background-inverse": "#000000",
        "--border-default": "#000000",
        "--border-input": "#000000",
        "--border-input-hover": "#FF3A00",
        "--border-strong": "#000000",
        "--border-card": "#000000",
        "--border-inverse": "#000000",
        "--text-default": "#000000",
        "--text-muted": "#555555",
        "--text-alt": "#333333",
        "--text-inverse": "#ffffff",
        "--radius": "0px",
        "--radius-pill": "0px",
        "--radius-button": "0px",
        "--radius-input": "0px",
        "--radius-card": "0px",
        "--radius-card-lg": "0px",
        "--radius-card-sm": "0px",
        "--radius-dropdown": "0px",
        "--radius-modal": "0px",
        "--chart-1": "#FF3A00",
        "--chart-2": "#00E5FF",
        "--chart-3": "#FFE600",
        "--chart-4": "#FF00AA",
        "--chart-5": "#00FF66",
      },
      dark: {
        "--background-accent": "#FF5722",
        "--border-accent": "#FF5722",
        "--text-accent": "#FF5722",
        "--background-default": "#0A0A0A",
        "--background-alt": "#141414",
        "--background-medium": "#333333",
        "--background-muted": "#141414",
        "--background-inverse": "#ffffff",
        "--border-default": "#ffffff",
        "--border-input": "#ffffff",
        "--border-input-hover": "#FF5722",
        "--border-strong": "#ffffff",
        "--border-card": "#444444",
        "--border-inverse": "#ffffff",
        "--text-default": "#ffffff",
        "--text-muted": "#AAAAAA",
        "--text-alt": "#AAAAAA",
        "--text-inverse": "#000000",
        "--radius": "0px",
        "--radius-pill": "0px",
        "--radius-button": "0px",
        "--radius-input": "0px",
        "--radius-card": "0px",
        "--radius-card-lg": "0px",
        "--radius-card-sm": "0px",
        "--radius-dropdown": "0px",
        "--radius-modal": "0px",
        "--chart-1": "#FF5722",
        "--chart-2": "#00E5FF",
        "--chart-3": "#FFE600",
        "--chart-4": "#FF00AA",
        "--chart-5": "#00FF66",
      },
    },
  },
  {
    id: "soft-pastel",
    name: "Soft Pastel",
    description: "Gentle, muted pastels",
    preview: {
      accent: "#8B7EC8",
      background: "#FAFAFA",
      text: "#3A3552",
      muted: "#F0EDF8",
    },
    variables: {
      light: {
        "--background-accent": "#8B7EC8",
        "--border-accent": "#8B7EC8",
        "--text-accent": "#8B7EC8",
        "--background-default": "#FAFAFA",
        "--background-alt": "#F5F2FA",
        "--background-medium": "#C8BEE0",
        "--background-muted": "#F0EDF8",
        "--background-inverse": "#3A3552",
        "--border-default": "#E0DAF0",
        "--border-input": "#D2CAE4",
        "--border-input-hover": "#C8BEE0",
        "--border-strong": "#3A3552",
        "--border-card": "#E0DAF0",
        "--border-inverse": "#3A3552",
        "--text-default": "#3A3552",
        "--text-muted": "#8A82A0",
        "--text-alt": "#6A6280",
        "--text-inverse": "#FAFAFA",
        "--background-danger": "#E8A0A0",
        "--background-success": "#A0D8A0",
        "--background-info": "#A0C0E8",
        "--background-warning": "#E8D0A0",
        "--border-danger": "#E8A0A0",
        "--border-success": "#A0D8A0",
        "--border-warning": "#E8D0A0",
        "--border-info": "#A0C0E8",
        "--text-danger": "#C07070",
        "--text-success": "#70A870",
        "--text-warning": "#C0A060",
        "--text-info": "#7090C0",
        "--radius-card": "16px",
        "--radius-card-lg": "20px",
        "--radius-card-sm": "14px",
        "--radius-dropdown": "14px",
        "--radius-modal": "20px",
        "--chart-1": "#C8A8E0",
        "--chart-2": "#A8C8E8",
        "--chart-3": "#E8B0B0",
        "--chart-4": "#B0D8B0",
        "--chart-5": "#E8D0A8",
      },
      dark: {
        "--background-accent": "#A898E0",
        "--border-accent": "#A898E0",
        "--text-accent": "#A898E0",
        "--background-default": "#14121C",
        "--background-alt": "#1E1A2A",
        "--background-medium": "#3A3452",
        "--background-muted": "#1E1A2A",
        "--background-inverse": "#FAFAFA",
        "--border-default": "#2A2640",
        "--border-input": "#2A2640",
        "--border-input-hover": "#4A4468",
        "--border-strong": "#A898E0",
        "--border-card": "#2A2640",
        "--border-inverse": "#FAFAFA",
        "--text-default": "#E8E4F4",
        "--text-muted": "#8A82A0",
        "--text-alt": "#8A82A0",
        "--text-inverse": "#14121C",
        "--background-danger": "#D08080",
        "--background-success": "#80C080",
        "--background-info": "#80A8D8",
        "--background-warning": "#D8C080",
        "--border-danger": "#D08080",
        "--border-success": "#80C080",
        "--border-warning": "#D8C080",
        "--border-info": "#80A8D8",
        "--text-danger": "#E0A0A0",
        "--text-success": "#A0D8A0",
        "--text-warning": "#E0C880",
        "--text-info": "#A0C0E8",
        "--radius-card": "16px",
        "--radius-card-lg": "20px",
        "--radius-card-sm": "14px",
        "--radius-dropdown": "14px",
        "--radius-modal": "20px",
        "--chart-1": "#C8A8E0",
        "--chart-2": "#A8C8E8",
        "--chart-3": "#E8B0B0",
        "--chart-4": "#B0D8B0",
        "--chart-5": "#E8D0A8",
      },
    },
  },
];
