import { readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  buildSkillMd,
  writeContextBundle,
} from "../../src/core/context/index.js";
import { buildTokensCss } from "../../src/core/context/tokens-css.js";
import type { Fingerprint } from "../../src/core/types.js";

const EXPRESSION: Fingerprint = {
  id: "sample-ds",
  source: "llm",
  timestamp: "2026-04-17T00:00:00.000Z",
  observation: {
    summary: "Restrained, utilitarian — warm neutrals on black.",
    personality: ["restrained", "utilitarian"],
    distinctiveTraits: ["true-black backgrounds", "tight type scale"],
    closestSystems: ["Vercel", "Linear"],
  },
  decisions: [
    {
      dimension: "color-strategy",
      decision: "Pure black backgrounds; warm off-white foreground.",
      evidence: ["--bg: #000", "--fg: #f5f5f0"],
    },
  ],
  palette: {
    dominant: [{ role: "accent", value: "#00d64f" }],
    neutrals: { steps: ["#000", "#111", "#222", "#f5f5f0"], count: 4 },
    semantic: [
      { role: "surface", value: "#000" },
      { role: "text", value: "#f5f5f0" },
    ],
    saturationProfile: "muted",
    contrast: "high",
  },
  spacing: { scale: [4, 8, 16, 24], baseUnit: 8, regularity: 0.9 },
  typography: {
    families: ["Inter", "ui-sans-serif"],
    sizeRamp: [14, 16, 20, 32],
    weightDistribution: { 400: 0.7, 500: 0.3 },
    lineHeightPattern: "normal",
  },
  surfaces: {
    borderRadii: [4, 8, 12],
    shadowComplexity: "subtle",
    borderUsage: "minimal",
  },
  embedding: [0, 0, 0, 0],
};

let dir: string;
beforeEach(async () => {
  dir = join(
    tmpdir(),
    `ghost-context-test-${Date.now()}-${Math.random().toString(36).slice(2)}`,
  );
});
afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

describe("writeContextBundle", () => {
  it("default: emits SKILL.md + fingerprint.md + tokens.css", async () => {
    const res = await writeContextBundle(EXPRESSION, { outDir: dir });
    const names = res.files.map((f) => f.split("/").pop());
    expect(names).toEqual(["SKILL.md", "fingerprint.md", "tokens.css"]);

    const skill = await readFile(res.files[0], "utf-8");
    expect(skill).toContain("user-invocable: true");
    expect(skill).toContain("name: sample-ds");
    expect(skill).toContain("tokens.css");
  });

  it("--no-tokens: emits SKILL.md + fingerprint.md only", async () => {
    const res = await writeContextBundle(EXPRESSION, {
      outDir: dir,
      tokens: false,
    });
    const names = res.files.map((f) => f.split("/").pop());
    expect(names).toEqual(["SKILL.md", "fingerprint.md"]);

    const skill = await readFile(res.files[0], "utf-8");
    expect(skill).not.toContain("tokens.css");
  });

  it("--readme: adds README.md on top of the default bundle", async () => {
    const res = await writeContextBundle(EXPRESSION, {
      outDir: dir,
      readme: true,
    });
    const names = res.files.map((f) => f.split("/").pop());
    expect(names).toEqual([
      "SKILL.md",
      "fingerprint.md",
      "tokens.css",
      "README.md",
    ]);
  });

  it("--prompt-only: emits a single prompt.md", async () => {
    const res = await writeContextBundle(EXPRESSION, {
      outDir: dir,
      promptOnly: true,
    });
    expect(res.files).toHaveLength(1);
    const prompt = await readFile(res.files[0], "utf-8");
    expect(prompt).toContain("# Character");
    expect(prompt).toContain("# Signature");
    expect(prompt).toContain("# Decisions");
  });

  it("honors --name override in SKILL frontmatter", async () => {
    const md = buildSkillMd(EXPRESSION, "my-custom-name", false);
    expect(md).toMatch(/^---\nname: my-custom-name\n/);
  });

  it("tokens.css carries a provenance header with source path and timestamp", async () => {
    const res = await writeContextBundle(EXPRESSION, {
      outDir: dir,
      sourcePath: "/path/to/fingerprint.md",
      generator: "ghost@0.9.0",
    });
    const cssFile = res.files.find((f) => f.endsWith("tokens.css"));
    if (!cssFile) throw new Error("tokens.css missing from output");
    const css = await readFile(cssFile, "utf-8");
    expect(css).toMatch(/Generated by ghost@0\.9\.0/);
    expect(css).toContain("/path/to/fingerprint.md");
    expect(css).toContain("DO NOT EDIT");
    expect(css).toContain("2026-04-17T00:00:00.000Z");
  });

  it("legacy format: 'bundle' still emits README + tokens (back-compat)", async () => {
    const res = await writeContextBundle(EXPRESSION, {
      outDir: dir,
      format: "bundle",
    });
    const names = res.files.map((f) => f.split("/").pop());
    expect(names).toContain("tokens.css");
    expect(names).toContain("README.md");
  });
});

describe("buildTokensCss", () => {
  it("emits only dimensions present on the fingerprint", () => {
    const minimal: Fingerprint = {
      ...EXPRESSION,
      typography: {
        families: [],
        sizeRamp: [],
        weightDistribution: {},
        lineHeightPattern: "normal",
      },
      surfaces: {
        borderRadii: [],
        shadowComplexity: "none",
        borderUsage: "minimal",
      },
    };
    const css = buildTokensCss(minimal);
    expect(css).toContain("/* Spacing scale */");
    expect(css).not.toContain("/* Typography scale */");
    expect(css).not.toContain("/* Font families */");
    expect(css).not.toContain("/* Border radii */");
  });
});
